name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: root
          server: 34.131.24.196
          port: 22
          local_path: './*'
          remote_path: '/home/quickhills/public_html/admin'
          sftp_only: true
          password: ${{ secrets.SERVER_PASSWORD }}
          
      - name: Run optimization
        uses: appleboy/ssh-action@master
        with:
          host: 34.131.24.196
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /home/quickhills/public_html/admin
            php artisan optimize:clear
