name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
          ssh-keyscan -t rsa 34.131.24.196 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no root@34.131.24.196 '
            cd /home/quickhills/public_html/admin && 
            git config --global --add safe.directory /home/quickhills/public_html/admin &&
            git pull origin main &&
            php artisan optimize:clear
          '
