name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key to runner
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          
      - name: Adding Known Hosts
        run: ssh-keyscan -H 34.131.24.196 >> ~/.ssh/known_hosts
          
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy code
        run: |
          rsync -avz --exclude '.git/' ./ root@34.131.24.196:/home/quickhills/public_html/admin/
          
      - name: Run optimization
        run: |
          ssh root@34.131.24.196 'cd /home/quickhills/public_html/admin && php artisan optimize:clear'
